### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar una sola pelicula
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recuperar todas las peliculas por genero
GET http://localhost:1234/movies?genre=fantasy

### Crear una nueva pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "The Godfather 2",
  "year": 1972,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
  "genre": ["Drama", "Crime"],
  "rate": 9.2
}

### Actualizar una pelicula
PATCH  http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "year": 2000
}